vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /images/article
            upload_destination: "%kernel.project_dir%/public/image/article"
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            # inject_on_load: false
            # delete_on_update: true
            # delete_on_remove: true
